/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tempatfotocopy;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author TEGUH_ADIGUNA
 */
public class MenuPembayaran extends javax.swing.JFrame {
    private DefaultTableModel model;
    private int idPembayaranTerpilih = -1;
    /**
     * Creates new form MenuPembayaran
     */
    public MenuPembayaran() {
        initComponents();
        setLocationRelativeTo(null);
         buatTabel();
        isiMetodeBayar();
        tampilData();
        kosongkanForm();

        txtTotalTagihan.setEditable(false);
        txtKembalian.setEditable(false);

        pasangHitungOtomatis();
    }
    
private void buatTabel() {

    model = new DefaultTableModel();

    model.addColumn("ID Pembayaran");
    model.addColumn("ID Transaksi");
    model.addColumn("Total Tagihan");
    model.addColumn("Total Bayar");
    model.addColumn("Kembalian");
    model.addColumn("Metode Bayar");

    tblPembayaran.setModel(model);
}
private void isiMetodeBayar() {

    cmbMetode.removeAllItems();

    cmbMetode.addItem("===Pilih Metode===");
    cmbMetode.addItem("CASH");
    cmbMetode.addItem("QRIS");
    cmbMetode.addItem("TRANSFER");
}
private void kosongkanForm() {

    idPembayaranTerpilih = -1;

    txtIdTransaksi.setText("");
    txtTotalTagihan.setText("");
    txtTotalBayar.setText("");
    txtKembalian.setText("");

    cmbMetode.setSelectedIndex(0);

    txtIdTransaksi.setEditable(true);
    txtIdTransaksi.requestFocus();
}
private void tampilData() {

    model.setRowCount(0);

    try {

        Connection conn =
                TempatFotocopy.getKoneksi();

        String sql =
                "SELECT p.id_pembayaran, "
                + "p.id_transaksi, "
                + "t.total_harga, "
                + "p.total_bayar, "
                + "p.kembalian, "
                + "p.metode_bayar "
                + "FROM pembayaran p "
                + "JOIN transaksi t "
                + "ON p.id_transaksi = t.id_transaksi "
                + "ORDER BY p.id_pembayaran DESC";

        PreparedStatement pst =
                conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id_pembayaran"),
                rs.getInt("id_transaksi"),
                rs.getBigDecimal("total_harga"),
                rs.getBigDecimal("total_bayar"),
                rs.getBigDecimal("kembalian"),
                rs.getString("metode_bayar")
            });
        }

        rs.close();
        pst.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Error menampilkan pembayaran: "
                + e.getMessage()
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnDash = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnNota = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembayaran = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTotalTagihan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        txtIdTransaksi = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        cmbMetode = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBackground(new java.awt.Color(114, 136, 174));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logo admin (3).png"))); // NOI18N

        btnDash.setBackground(new java.awt.Color(0, 153, 255));
        btnDash.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDash.setText("DASHBOARD");
        btnDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(0, 153, 255));
        btnTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTransaksi.setText("TRANSAKSI");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnPembayaran.setBackground(new java.awt.Color(0, 153, 255));
        btnPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPembayaran.setText("PEMBAYARAN");
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnNota.setBackground(new java.awt.Color(0, 153, 255));
        btnNota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNota.setText("CEK NOTA");
        btnNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(33, 33, 33))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btnDash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNota, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEMBAYARAN");

        tblPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPembayaran);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Transaksi");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Tagihan");

        txtTotalTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalTagihanActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Bayar");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kembalian");

        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });

        txtIdTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdTransaksiMouseClicked(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(66, 116, 217));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(66, 116, 217));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(66, 116, 217));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Metode Bayar");

        cmbMetode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "===Pilih Kategori===", "Tunai", "Qris", "Transfer" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTotalTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(113, 113, 113)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(cmbMetode, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(btnTambah)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnEdit)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnSimpan)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnHapus)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotalTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtIdTransaksi)
                    .addComponent(txtTotalBayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(cmbMetode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void txtTotalTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalTagihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalTagihanActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (idPembayaranTerpilih == -1) {

        JOptionPane.showMessageDialog(
                null,
                "Pilih data pembayaran dari tabel"
        );

        return;
    }

    int jawab =
            JOptionPane.showConfirmDialog(
                null,
                "Yakin ingin menghapus pembayaran ini?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
            );

    if (jawab == JOptionPane.YES_OPTION) {

        try {

            Connection conn =
                    TempatFotocopy.getKoneksi();

            String sql =
                    "DELETE FROM pembayaran "
                    + "WHERE id_pembayaran = ?";

            PreparedStatement pst =
                    conn.prepareStatement(sql);

            pst.setInt(
                    1,
                    idPembayaranTerpilih
            );

            pst.executeUpdate();
            pst.close();

            JOptionPane.showMessageDialog(
                    null,
                    "Data pembayaran berhasil dihapus"
            );

            tampilData();
            kosongkanForm();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Error menghapus pembayaran: "
                    + e.getMessage()
            );
        }
}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
         int jawab = JOptionPane.showConfirmDialog(
            null,
            "Yakin ingin logout?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

    if(jawab == JOptionPane.YES_OPTION){

        new login().setVisible(true);

        this.dispose();
    }
    
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void cariTransaksi() {

    String id = txtIdTransaksi.getText().trim();

    if (id.isEmpty()) {
        return;
    }

    try {

        Connection conn =
                TempatFotocopy.getKoneksi();

        String sql =
                "SELECT total_harga "
                + "FROM transaksi "
                + "WHERE id_transaksi = ?";

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setInt(
                1,
                Integer.parseInt(id)
        );

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            txtTotalTagihan.setText(
                    rs.getBigDecimal("total_harga")
                    .toPlainString()
            );

            txtTotalBayar.requestFocus();

        } else {

            JOptionPane.showMessageDialog(
                    null,
                    "ID transaksi tidak ditemukan"
            );

            txtTotalTagihan.setText("");
        }

        rs.close();
        pst.close();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                null,
                "ID transaksi harus berupa angka"
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Error mencari transaksi: "
                + e.getMessage()
        );
    }
}
private void hitungKembalian() {

    try {

        String tagihanText =
                txtTotalTagihan.getText().trim();

        String bayarText =
                txtTotalBayar.getText().trim();

        if (tagihanText.isEmpty()
                || bayarText.isEmpty()) {

            txtKembalian.setText("");
            return;
        }

        double tagihan =
                Double.parseDouble(tagihanText);

        double bayar =
                Double.parseDouble(bayarText);

        double kembalian =
                bayar - tagihan;

        if (kembalian >= 0) {

            txtKembalian.setText(
                    String.valueOf(kembalian)
            );

        } else {

            txtKembalian.setText("0");
        }

    } catch (NumberFormatException e) {

        txtKembalian.setText("");
    }
}
private void pasangHitungOtomatis() {

    txtTotalBayar.getDocument().addDocumentListener(
        new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                hitungKembalian();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                hitungKembalian();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                hitungKembalian();
            }
        }
    );
}
    private void txtIdTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdTransaksiMouseClicked
        // TODO add your handling code here:
         cariTransaksi();
    }//GEN-LAST:event_txtIdTransaksiMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
         String idTransaksi =
            txtIdTransaksi.getText().trim();

    String totalTagihan =
            txtTotalTagihan.getText().trim();

    String totalBayar =
            txtTotalBayar.getText().trim();

    String metode =
            cmbMetode.getSelectedItem().toString();

    if (idTransaksi.isEmpty()) {

        JOptionPane.showMessageDialog(
                null,
                "ID transaksi harus diisi"
        );

        return;
    }

    if (totalTagihan.isEmpty()) {

        JOptionPane.showMessageDialog(
                null,
                "Tekan ENTER pada ID transaksi "
                + "untuk mengambil total tagihan"
        );

        return;
    }

    if (totalBayar.isEmpty()) {

        JOptionPane.showMessageDialog(
                null,
                "Total bayar harus diisi"
        );

        return;
    }

    if (metode.equals("===Pilih Metode===")) {

        JOptionPane.showMessageDialog(
                null,
                "Silakan pilih metode bayar"
        );

        return;
    }

    try {

        double tagihan =
                Double.parseDouble(totalTagihan);

        double bayar =
                Double.parseDouble(totalBayar);

        if (bayar < tagihan) {

            JOptionPane.showMessageDialog(
                    null,
                    "Uang pembayaran kurang!\n"
                    + "Total Tagihan: " + tagihan + "\n"
                    + "Total Bayar: " + bayar
            );

            return;
        }

        double kembalian =
                bayar - tagihan;

        Connection conn =
                TempatFotocopy.getKoneksi();

        // Cek apakah transaksi sudah dibayar
        String cekSql =
                "SELECT id_pembayaran "
                + "FROM pembayaran "
                + "WHERE id_transaksi = ?";

        PreparedStatement cek =
                conn.prepareStatement(cekSql);

        cek.setInt(
                1,
                Integer.parseInt(idTransaksi)
        );

        ResultSet rs = cek.executeQuery();

        if (rs.next()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Transaksi ini sudah dibayar"
            );

            rs.close();
            cek.close();
            return;
        }

        rs.close();
        cek.close();

        // Simpan pembayaran
        String sql =
                "INSERT INTO pembayaran "
                + "(id_transaksi, total_bayar, "
                + "kembalian, metode_bayar) "
                + "VALUES (?, ?, ?, ?)";

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setInt(
                1,
                Integer.parseInt(idTransaksi)
        );

        pst.setDouble(2, bayar);
        pst.setDouble(3, kembalian);
        pst.setString(4, metode);

        pst.executeUpdate();
        pst.close();

        JOptionPane.showMessageDialog(
                null,
                "Pembayaran berhasil disimpan"
        );

        tampilData();
        kosongkanForm();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                null,
                "ID transaksi dan total bayar "
                + "harus berupa angka"
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Error menyimpan pembayaran: "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembayaranMouseClicked
        // TODO add your handling code here:
        int baris =
            tblPembayaran.getSelectedRow();

    if (baris != -1) {

        idPembayaranTerpilih =
                Integer.parseInt(
                    tblPembayaran
                    .getValueAt(baris, 0)
                    .toString()
                );

        txtIdTransaksi.setText(
                tblPembayaran
                .getValueAt(baris, 1)
                .toString()
        );

        txtTotalTagihan.setText(
                tblPembayaran
                .getValueAt(baris, 2)
                .toString()
        );

        txtTotalBayar.setText(
                tblPembayaran
                .getValueAt(baris, 3)
                .toString()
        );

        txtKembalian.setText(
                tblPembayaran
                .getValueAt(baris, 4)
                .toString()
        );

        cmbMetode.setSelectedItem(
                tblPembayaran
                .getValueAt(baris, 5)
                .toString()
        );

        txtIdTransaksi.setEditable(false);
    }
    }//GEN-LAST:event_tblPembayaranMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (idPembayaranTerpilih == -1) {

        JOptionPane.showMessageDialog(
                null,
                "Pilih data pembayaran dari tabel"
        );

        return;
    }

    String totalBayar =
            txtTotalBayar.getText().trim();

    String totalTagihan =
            txtTotalTagihan.getText().trim();

    String metode =
            cmbMetode.getSelectedItem().toString();

    if (totalBayar.isEmpty()) {

        JOptionPane.showMessageDialog(
                null,
                "Total bayar harus diisi"
        );

        return;
    }

    if (metode.equals("===Pilih Metode===")) {

        JOptionPane.showMessageDialog(
                null,
                "Pilih metode bayar"
        );

        return;
    }

    try {

        double tagihan =
                Double.parseDouble(totalTagihan);

        double bayar =
                Double.parseDouble(totalBayar);

        if (bayar < tagihan) {

            JOptionPane.showMessageDialog(
                    null,
                    "Total bayar kurang dari tagihan"
            );

            return;
        }

        double kembalian =
                bayar - tagihan;

        Connection conn =
                TempatFotocopy.getKoneksi();

        String sql =
                "UPDATE pembayaran SET "
                + "total_bayar = ?, "
                + "kembalian = ?, "
                + "metode_bayar = ? "
                + "WHERE id_pembayaran = ?";

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setDouble(1, bayar);
        pst.setDouble(2, kembalian);
        pst.setString(3, metode);
        pst.setInt(4, idPembayaranTerpilih);

        pst.executeUpdate();
        pst.close();

        JOptionPane.showMessageDialog(
                null,
                "Data pembayaran berhasil diubah"
        );

        tampilData();
        kosongkanForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Error mengubah pembayaran: "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashActionPerformed
        // TODO add your handling code here:
        DashboardKasir Kasir = new DashboardKasir();
    Kasir.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnDashActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        MenuTransaksi Transaksi = new MenuTransaksi();
    Transaksi.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaActionPerformed
        // TODO add your handling code here:
                CekNota Nota = new CekNota();
    Nota.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNota;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JComboBox<String> cmbMetode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPembayaran;
    private javax.swing.JTextField txtIdTransaksi;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtTotalBayar;
    private javax.swing.JTextField txtTotalTagihan;
    // End of variables declaration//GEN-END:variables
}
