/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tempatfotocopy;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author TEGUH_ADIGUNA
 */
public class MenuTransaksi extends javax.swing.JFrame {
    private DefaultTableModel model;
    private int idTransaksiTerpilih = -1;
    /**
     * Creates new form MenuTransaksi
     */
    public MenuTransaksi() {
        initComponents();
        setLocationRelativeTo(null);
        tampilLayanan();
        buatTabel();
        tampilData();
        kosongkanForm();

        txtIdTransaksi.setEditable(false);
        txtTanggal.setEditable(false);
        txtIdUser.setEditable(false);
    }
private void buatTabel() {

    model = new DefaultTableModel();

    model.addColumn("ID Transaksi");
    model.addColumn("Tanggal");
    model.addColumn("ID User");
    model.addColumn("Kasir");
    model.addColumn("ID Pelanggan");
    model.addColumn("Pelanggan");
    model.addColumn("Total Harga");

    tblTransaksi.setModel(model);
}
private void tampilData() {

    model.setRowCount(0);

    try {

        Connection conn =
                TempatFotocopy.getKoneksi();

        String sql =
                "SELECT t.id_transaksi, "
                + "t.tanggal, "
                + "t.id_user, "
                + "u.nama_user, "
                + "t.id_pelanggan, "
                + "p.nama_pelanggan, "
                + "t.total_harga "
                + "FROM transaksi t "
                + "JOIN user u "
                + "ON t.id_user = u.id_user "
                + "JOIN pelanggan p "
                + "ON t.id_pelanggan = p.id_pelanggan "
                + "ORDER BY t.id_transaksi DESC";

        PreparedStatement pst =
                conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id_transaksi"),
                rs.getDate("tanggal"),
                rs.getInt("id_user"),
                rs.getString("nama_user"),
                rs.getInt("id_pelanggan"),
                rs.getString("nama_pelanggan"),
                rs.getBigDecimal("total_harga")
            });
        }

        rs.close();
        pst.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Error menampilkan transaksi: "
                + e.getMessage()
        );
    }
}
private void kosongkanForm() {

    idTransaksiTerpilih = -1;

    // ID transaksi otomatis database
    txtIdTransaksi.setText("");

    // Tanggal otomatis hari ini
    txtTanggal.setText(
        java.time.LocalDate.now().toString()
    );

    // ID user otomatis dari kasir login
    txtIdUser.setText(
        String.valueOf(Session.idUser)
    );

    // ID pelanggan diketik berdasarkan Data Pelanggan
    txtIdPelanggan.setText("");

    txtTotalHarga.setText("");

    txtIdPelanggan.requestFocus();
}
private void tampilLayanan() {

    try {

        Connection conn = TempatFotocopy.getKoneksi();

        String sql = "SELECT nama_layanan FROM layanan ORDER BY nama_layanan";

        PreparedStatement ps = conn.prepareStatement(sql);

        ResultSet rs = ps.executeQuery();

        cmbLayanan.removeAllItems();

        while (rs.next()) {

            cmbLayanan.addItem(rs.getString("nama_layanan"));

        }

        rs.close();
        ps.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e.getMessage());

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnDash = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnNota = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdTransaksi = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        txtIdUser = new javax.swing.JTextField();
        txtIdPelanggan = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSImpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbLayanan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logo admin (3).png"))); // NOI18N

        btnDash.setBackground(new java.awt.Color(0, 153, 255));
        btnDash.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDash.setText("DASHBOARD");
        btnDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(0, 153, 255));
        btnTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTransaksi.setText("TRANSAKSI");

        btnPembayaran.setBackground(new java.awt.Color(0, 153, 255));
        btnPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPembayaran.setText("PEMBAYARAN");
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnNota.setBackground(new java.awt.Color(0, 153, 255));
        btnNota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNota.setText("CEK NOTA");
        btnNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(33, 33, 33))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnDash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNota, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSAKSI");

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Transaksi");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal Transaksi");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID User");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID Pelanggan");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Harga");

        btnTambah.setBackground(new java.awt.Color(66, 116, 217));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(66, 116, 217));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSImpan.setBackground(new java.awt.Color(66, 116, 217));
        btnSImpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSImpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSImpan.setText("SIMPAN");
        btnSImpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSImpanActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Layanan");

        cmbLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTambah))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(79, 79, 79)
                                                .addComponent(jLabel5))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7)
                                                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(56, 56, 56)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel8)
                                                    .addComponent(btnHapus)
                                                    .addComponent(txtIdUser, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                                    .addComponent(cmbLayanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(btnEdit)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnSImpan)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSImpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
         int jawab = JOptionPane.showConfirmDialog(
            null,
            "Yakin ingin logout?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

    if(jawab == JOptionPane.YES_OPTION){

        new login().setVisible(true);

        this.dispose();
    }                   
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSImpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSImpanActionPerformed
        // TODO add your handling code here:
        String tanggal = txtTanggal.getText().trim();
        String idPelanggan = txtIdPelanggan.getText().trim();
        String totalHarga = txtTotalHarga.getText().trim();

    // CEK SESSION USER
    if (Session.idUser <= 0) {
        JOptionPane.showMessageDialog(
            null,
            "ID User tidak ditemukan. Silakan login ulang."
        );
        return;
    }

    // CEK ID PELANGGAN
    if (idPelanggan.isEmpty()) {
        JOptionPane.showMessageDialog(
            null,
            "ID Pelanggan harus diisi"
        );
        return;
    }

    // CEK TOTAL HARGA
    if (totalHarga.isEmpty()) {
        JOptionPane.showMessageDialog(
            null,
            "Total Harga harus diisi"
        );
        return;
    }

    try {

        int idPelangganInt =
            Integer.parseInt(idPelanggan);

        double total =
            Double.parseDouble(totalHarga);

        Connection conn =
            TempatFotocopy.getKoneksi();

        String cekSql =
            "SELECT id_pelanggan, nama_pelanggan "
            + "FROM pelanggan "
            + "WHERE id_pelanggan = ?";

        PreparedStatement cek =
            conn.prepareStatement(cekSql);

        cek.setInt(1, idPelangganInt);

        ResultSet rs =
            cek.executeQuery();

        // JIKA ID PELANGGAN TIDAK ADA
        if (!rs.next()) {

            JOptionPane.showMessageDialog(
                null,
                "ID Pelanggan " + idPelangganInt
                + " tidak ditemukan di Data Pelanggan"
            );

            rs.close();
            cek.close();
            return;
        }

        // Ambil nama pelanggan
        String namaPelanggan =
            rs.getString("nama_pelanggan");

        rs.close();
        cek.close();

        String sql =
            "INSERT INTO transaksi "
            + "(tanggal, id_user, "
            + "id_pelanggan, total_harga) "
            + "VALUES (?, ?, ?, ?)";

        PreparedStatement pst =
            conn.prepareStatement(sql);

        pst.setDate(
            1,
            java.sql.Date.valueOf(tanggal)
        );

        // ID USER OTOMATIS DARI LOGIN
        pst.setInt(
            2,
            Session.idUser
        );

        // ID PELANGGAN DARI DATA PELANGGAN
        pst.setInt(
            3,
            idPelangganInt
        );

        pst.setDouble(
            4,
            total
        );

        pst.executeUpdate();
        pst.close();

        JOptionPane.showMessageDialog(
            null,
            "Transaksi berhasil disimpan\n"
            + "Pelanggan: " + namaPelanggan
        );

        tampilData();
        kosongkanForm();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
            null,
            "ID Pelanggan dan Total Harga harus berupa angka"
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            null,
            "Error menyimpan transaksi: "
            + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnSImpanActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        int baris =
            tblTransaksi.getSelectedRow();

    if (baris != -1) {

        idTransaksiTerpilih =
                Integer.parseInt(
                    tblTransaksi
                    .getValueAt(baris, 0)
                    .toString()
                );

        txtIdTransaksi.setText(
                tblTransaksi
                .getValueAt(baris, 0)
                .toString()
        );

        txtTanggal.setText(
                tblTransaksi
                .getValueAt(baris, 1)
                .toString()
        );

        txtIdUser.setText(
                tblTransaksi
                .getValueAt(baris, 2)
                .toString()
        );

        txtIdPelanggan.setText(
                tblTransaksi
                .getValueAt(baris, 4)
                .toString()
        );

        txtTotalHarga.setText(
                tblTransaksi
                .getValueAt(baris, 6)
                .toString()
        );
    }
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (idTransaksiTerpilih == -1) {

        JOptionPane.showMessageDialog(
                null,
                "Pilih transaksi dari tabel"
        );

        return;
    }

    String tanggal =
            txtTanggal.getText().trim();

    String idUser =
            txtIdUser.getText().trim();

    String idPelanggan =
            txtIdPelanggan.getText().trim();

    String totalHarga =
            txtTotalHarga.getText().trim();

    if (idUser.isEmpty()
            || idPelanggan.isEmpty()
            || totalHarga.isEmpty()) {

        JOptionPane.showMessageDialog(
                null,
                "Semua data harus diisi"
        );

        return;
    }

    try {

        Connection conn =
                TempatFotocopy.getKoneksi();

        String sql =
                "UPDATE transaksi SET "
                + "tanggal = ?, "
                + "id_user = ?, "
                + "id_pelanggan = ?, "
                + "total_harga = ? "
                + "WHERE id_transaksi = ?";

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setDate(
                1,
                Date.valueOf(tanggal)
        );

        pst.setInt(
                2,
                Integer.parseInt(idUser)
        );

        pst.setInt(
                3,
                Integer.parseInt(idPelanggan)
        );

        pst.setDouble(
                4,
                Double.parseDouble(totalHarga)
        );

        pst.setInt(
                5,
                idTransaksiTerpilih
        );

        pst.executeUpdate();
        pst.close();

        JOptionPane.showMessageDialog(
                null,
                "Transaksi berhasil diubah"
        );

        tampilData();
        kosongkanForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Error mengubah transaksi: "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
         if (idTransaksiTerpilih == -1) {

        JOptionPane.showMessageDialog(
                null,
                "Pilih transaksi dari tabel"
        );

        return;
    }

    int jawab =
            JOptionPane.showConfirmDialog(
                null,
                "Yakin ingin menghapus transaksi ini?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
            );

    if (jawab == JOptionPane.YES_OPTION) {

        try {

            Connection conn =
                    TempatFotocopy.getKoneksi();

            String sql =
                    "DELETE FROM transaksi "
                    + "WHERE id_transaksi = ?";

            PreparedStatement pst =
                    conn.prepareStatement(sql);

            pst.setInt(
                    1,
                    idTransaksiTerpilih
            );

            pst.executeUpdate();
            pst.close();

            JOptionPane.showMessageDialog(
                    null,
                    "Transaksi berhasil dihapus"
            );

            tampilData();
            kosongkanForm();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Error menghapus transaksi: "
                    + e.getMessage()
            );
        }
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashActionPerformed
        // TODO add your handling code here:
        DashboardKasir Kasir = new DashboardKasir();
    Kasir.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnDashActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
        MenuPembayaran Pembayaran = new MenuPembayaran();
    Pembayaran.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaActionPerformed
        // TODO add your handling code here:
        CekNota Nota = new CekNota();
    Nota.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNota;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnSImpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JComboBox<String> cmbLayanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtIdPelanggan;
    private javax.swing.JTextField txtIdTransaksi;
    private javax.swing.JTextField txtIdUser;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
